# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-01 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='character',
            field=models.CharField(default='', max_length=200),
        ),
    ]
