# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-09 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0002_product_character'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=200)),
                ('Tlf', models.IntegerField()),
                ('cost', models.FloatField()),
                ('order', models.IntegerField()),
            ],
        ),
    ]
